# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

source 'https://github.com/INFOCITY/richflyer-specs.git'

target 'RichFlyerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RichFlyerApp
  pod 'SwiftRichFlyer', '3.2.3'
  pod 'SwiftRichFlyerEvent', '3.1.5'
  
    target 'NotificationContent' do
    inherit! :search_paths
  end

  target 'NotificationService' do
    inherit! :search_paths
  end

end
